Repository Mango-Butter/dev-fe, pull requests merged in 2025-05, with the labels that each got.

#21 [#20] 망고버터 아이콘 ver.1 추가
  dev-dist/sw.js
  src/components/icons/BusinessIcon.tsx
  src/components/icons/CalendarIcon.tsx
  src/components/icons/CameraIcon.tsx
  src/components/icons/CheckboxIcon.tsx
  src/components/icons/CloseIcon.tsx
  src/components/icons/CoinIcon.tsx
  src/components/icons/DownloadIcon.tsx
  src/components/icons/EditIcon.tsx
  src/components/icons/ErrorIcon.tsx
  src/components/icons/HomeIcon.tsx
  src/components/icons/ImageIcon.tsx
  src/components/icons/PersonIcon.tsx
  src/components/icons/RadioIcon.tsx
  src/components/icons/ResetIcon.tsx
  src/components/icons/StoreIcon.tsx
  src/components/icons/TimeIcon.tsx
  src/components/icons/UploadIcon.tsx
  yarn.lock
Labels: design

#24 [#19] 매장 관련 기능 개발
  dev-dist/sw.js
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/api/schedule.ts
  src/api/staff.ts
  src/api/store.ts
  src/components/common/GpsMapPreview.tsx
  src/components/common/RangeDatePicker.tsx
  src/components/common/SelectField.tsx
  src/components/common/SingleDatePicker.tsx
  src/components/common/TextField.tsx
  src/components/icons/MailIcon.tsx
  src/components/icons/MenuIcon.tsx
  src/components/icons/PinLocationIcon.tsx
  src/components/layouts/BottomSheet.tsx
  src/components/layouts/MobileHeader.tsx
  src/components/layouts/MobileLayout.tsx
  src/hooks/useDateDisplay.ts
  src/hooks/useScrollLock.ts
  src/main.tsx
  src/pages/Employees.tsx
  src/pages/Schedule.tsx
  src/pages/Store.tsx
  src/pages/Task.tsx
  src/pages/employee/Employees.tsx
  src/pages/employee/RegularScheduleAddForm.tsx
  src/pages/schedule/Schedule.tsx
  src/pages/schedule/ScheduleAddForm.tsx
  src/pages/schedule/SingleScheduleAddForm.tsx
  src/pages/signup/Signup.tsx
  src/pages/store/AttendanceSettingPage.tsx
  src/pages/store/NotificationSettingPage.tsx
  src/pages/store/SalarySettingPage.tsx
  src/pages/store/Store.tsx
  src/pages/store/StoreBottomSheetContent.tsx
  src/pages/store/StoreInfoEditPage.tsx
  src/pages/store/StoreInfoPage.tsx
  src/schemas/storeSchema.ts
  src/stores/storeStore.ts
  src/stores/useBottomSheetStore.ts
  src/stores/useScheduleStore.ts
  src/stores/userStore.ts
  src/styles/calendar.css
  src/styles/datePickerCalendar.css
  src/styles/schedulePageCalendar.css
  src/types/common.ts
  src/types/schedule.ts
  src/types/staff.ts
  src/types/store.ts
  src/utils/date.ts
  tailwind.config.ts
Labels: design, feat

#25 [#16] 캘린더 페이지 스케줄 기능 개발
  dev-dist/sw.js
  src/api/calendar.ts
  src/api/schedule.ts
  src/api/staff.ts
  src/api/store.ts
  src/components/common/Label.tsx
  src/components/common/SingleDatePicker.tsx
  src/hooks/useScheduleFilters.ts
  src/pages/Home.tsx
  src/pages/schedule/AttendanceAddForm.tsx
  src/pages/schedule/AttendanceEditForm.tsx
  src/pages/schedule/Schedule.tsx
  src/pages/schedule/ScheduleAddForm.tsx
  src/pages/schedule/ScheduleFilter.tsx
  src/pages/schedule/SingleScheduleAddForm.tsx
  src/pages/schedule/SingleScheduleEditForm.tsx
  src/pages/store/AttendanceSettingPage.tsx
  src/pages/store/Store.tsx
  src/pages/store/StoreBottomSheetContent.tsx
  src/pages/store/StoreInfoPage.tsx
  src/pages/store/StoreRegisterPage.tsx
  src/stores/storeStore.ts
  src/stores/useScheduleStore.ts
  src/stores/userStore.ts
  src/styles/datePickerCalendar.css
  src/types/calendar.ts
  src/types/schedule.ts
  src/types/store.ts
  src/utils/attendance.ts
  src/utils/date.ts
  src/utils/time.ts
Labels: design, feat

#23 [#22] 근로계약서 퍼블리싱
  public/SignUpBoss.svg
  public/SignUpStaff.svg
  src/App.tsx
  src/components/layouts/Header.tsx
  src/pages/contract/Contract.tsx
  src/pages/contract/ContractDetailPage.tsx
  src/pages/contract/ContractRegisterPage.tsx
  src/pages/contract/ContractWritePage.tsx
  src/pages/signup/SignupStep1.tsx
Labels: design

#28 [#26] 망고보스 랜딩페이지 퍼블리싱
  dev-dist/sw.js
  src/App.tsx
  src/components/icons/BriefCaseIcon.tsx
  src/components/icons/ClockIcon.tsx
  src/components/icons/DateIcon.tsx
  src/components/icons/FolderIcon.tsx
  src/components/icons/LandingArror.tsx
  src/components/icons/LandingCoin.tsx
  src/components/icons/LandingDoc.tsx
  src/components/icons/LandingGroup.tsx
  src/components/icons/LandingProblem.tsx
  src/components/icons/LandingSign.tsx
  src/components/icons/LandingTimeMap.tsx
  src/components/icons/LandingTimeQR.tsx
  src/components/icons/Money.svg
  src/components/icons/MoneyIcon.tsx
  src/components/icons/PartyIcon.tsx
  src/components/icons/WatchIcon.tsx
  src/components/icons/WingMoneyIcon.tsx
  src/pages/auth/Landing.tsx
Labels: design, feat

#31 design: 회원가입 아이콘 수정(#22)
  src/components/icons/SignUpBoss.tsx
  src/components/icons/SignUpStaff.tsx
  src/pages/signup/SignupStep1.tsx
Labels: design

#34 [#33] 컴포넌트 아이콘 오류 해결
  dev-dist/sw.js
  src/components/icons/AlarmIcon.tsx
  src/components/icons/BriefCaseIcon.tsx
  src/components/icons/CoinIcon.tsx
  src/components/icons/DateIcon.tsx
  src/components/icons/FolderIcon.tsx
  src/components/icons/LandingArrow.tsx
  src/components/icons/LandingCoin.tsx
  src/components/icons/LandingDoc.tsx
  src/components/icons/LandingProblem.tsx
  src/components/icons/LandingSign.tsx
  src/components/icons/LandingTimeMap.tsx
  src/components/icons/LandingTimeQR.tsx
  src/components/icons/LogoIcon.tsx
  src/components/icons/MoneyIcon.tsx
  src/components/icons/PartyIcon.tsx
  src/components/icons/WingMoneyIcon.tsx
  src/pages/Landing.tsx
Labels: design

#38 [#15] 알바생 페이지 개발
  dev-dist/sw.js
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/api/boss/contract.ts
  src/api/staff/attendance.ts
  src/api/staff/calendar.ts
  src/api/staff/document.ts
  src/api/staff/schedule.ts
  src/api/staff/store.ts
  src/components/common/FileDropzone.tsx
  src/components/common/GpsMapPreview.tsx
  src/pages/attendance/staff/StaffAttendancePage.tsx
  src/pages/document/staff/DocumentSubmitBottomSheetContent.tsx
  src/pages/document/staff/StaffDocumentCard.tsx
  src/pages/document/staff/StaffDocumentListPage.tsx
  src/pages/document/staff/StaffDocumentPage.tsx
  src/pages/employee/boss/DocumentContainer.tsx
  src/pages/home/staff/HomeStaff.tsx
  src/pages/home/staff/StaffAttendanceCard.tsx
  src/pages/home/staff/StaffAttendanceContainer.tsx
  src/pages/home/staff/StaffDocumentRequestContainer.tsx
  src/pages/mypage/staff/MyPageStaff.tsx
  src/pages/mypage/staff/StaffDocumentContainer.tsx
  src/pages/mypage/staff/StaffMyPage.tsx
  src/pages/schedule/boss/StaffScheduleList.tsx
  src/pages/schedule/staff/ScheduleStaff.tsx
  src/schemas/attendanceSchema.ts
  src/stores/staff/documentStore.ts
  src/stores/staff/useStaffScheduleStore.ts
  src/styles/globals.css
  src/types/attendance.ts
  src/types/contract.ts
  src/types/document.ts
  src/utils/attendance.ts
  src/utils/compressImageIfNeeded.ts
  src/utils/fileToBase64.ts
Labels: design, feat

#47 [#46] 2차 QA
  dev-dist/sw.js
  src/api/boss/contract.ts
  src/libs/showConfirm.ts
  src/pages/contract/boss/ContractCard.tsx
  src/pages/contract/boss/ContractContainer.tsx
  src/pages/contract/boss/ContractViewPage.tsx
  src/pages/contract/staff/ContractViewStaffPage.tsx
  src/pages/document/boss/BossContractListPage.tsx
  src/pages/document/staff/StaffContractListPage.tsx
  src/pages/document/staff/StaffDocumentPage.tsx
  src/pages/employee/boss/RegularScheduleContainer.tsx
  src/pages/home/staff/StaffDocumentRequestContainer.tsx
  src/pages/mypage/staff/MyPageStaff.tsx
  src/pages/mypage/staff/StaffDocumentContainer.tsx
  src/pages/mypage/staff/StaffStoreBottomSheetContent.tsx
  src/pages/schedule/boss/AttendanceEditForm.tsx
  src/pages/store/boss/BossStoreCard.tsx
  src/pages/store/boss/StoreBottomSheetContent.tsx
  src/pages/store/boss/StoreModalContent.tsx
  src/pages/store/staff/StaffStoreCard.tsx
  src/pages/store/staff/StoreBottomSheetContentStaff.tsx
  src/types/contract.ts
Labels: fix, design

#49 [#48] 랜딩페이지 리팩토링 및 스토리북 적용
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/tsconfig.json
  dev-dist/sw.js
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/common/Button.stories.tsx
  src/components/common/Checkbox.stories.tsx
  src/components/common/TextField.stories.tsx
  src/pages/Landing.tsx
  src/pages/landing/FeatureCard.tsx
  src/pages/landing/Landing.tsx
  src/pages/landing/LandingDocLazy.tsx
  src/pages/landing/LandingDocSection.tsx
  src/pages/landing/LandingIntroLazy.tsx
  src/pages/landing/LandingIntroSection.tsx
  src/pages/landing/LandingPayLazy.tsx
  src/pages/landing/LandingPaySection.tsx
  vite.config.ts
  yarn.lock
Labels: refactor

#51 [#50] feat: PWA 설치 유도 및 FCM 푸시 알림 기능 추가
  .github/workflows/build-and-deploy.yaml
  dev-dist/sw.js
  package.json
  pnpm-lock.yaml
  public/firebase-messaging-sw.js
  src/App.tsx
  src/libs/fcm/UnifiedPWAPrompt.tsx
  src/libs/fcm/firebase.ts
  src/libs/fcm/messaging.tsx
  src/libs/fcm/requestPermission.ts
  src/routes/AppInitializer.tsx
Labels: feat
